org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.4
minecraft_version_lower_bound=1.21.4

fabric_enabled=true
neoforge_enabled=true

issue_url=https://github.com/SchmarrnDevs/Lighty/issues

mod_version=3.0.0-beta.8
maven_group=dev.schmarrn
mod_name=Lighty

fabric_loader_version=0.16.9
fabric_api_version=0.110.5+1.21.4

modmenu_version = 12.0.0-beta.1
iris_version = 1.8.0-beta.7+1.21.1

# neo stuff
neo_version=21.4.7-beta
minecraft_version_range=[1.21.4,1.22)
neo_version_range=[21.4.7-beta,)
loader_version_range=[2,)
mapping_channel=official
mapping_version=1.21.4
mod_id=lighty
mod_license=Apache-2.0
mod_authors=andi_makes, agnor99, Alveel
mod_description=The Light Overlay Mod with a twist!