modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/SchmarrnDevs/Lighty/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author} with help from ${credits}"
description = '''${description}'''
logoFile = "icon_high_res.png"
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"